# Generated by Django 6.0.3 on 2026-03-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(default='Trinity University', max_length=100),
        ),
    ]
